name: 'Add team label'
description: 'Add team label based on ticket number prefix in pull request title'

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v8
      with:
        script: |
          const {
            organization,
            pull_request,
            repository,
          } = context.payload;
          const { title } = pull_request
          
          const labels = [];
          if (/^D2-\d+:/.exec(title)) {
            labels.push('team-fun');
          }

          if (labels.length > 0) {
            console.log(`Adding team labels: ${labels}`);
            const owner = organization.login;
            const repo = repository.name;
            const issue_number = pull_request.number;
            const labels = ['test'];
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels
            });
          }
